import { AppLanguage, ExecutionOutputBundle, ExecutionOutputFile, OutputType } from '@/types';

export type CodeGenerationMode =
  | 'landing-page'
  | 'company-website'
  | 'dashboard'
  | 'crud-internal-tool'
  | 'uploader-processor-app'
  | 'small-game-prototype';

interface ModeInput {
  name: string;
  description: string;
  latestRevisionFeedback?: string | null;
  outputType: OutputType;
}

interface StabilizeInput {
  bundle: ExecutionOutputBundle;
  projectName: string;
  projectDescription: string;
  latestRevisionFeedback?: string | null;
  outputType: OutputType;
  language: AppLanguage;
}

const ENTRY_POINT_PRIORITY = [
  'index.html',
  'src/main.tsx',
  'src/main.ts',
  'app/page.tsx',
  'main.tsx',
  'main.ts',
  'src/index.tsx',
  'src/index.html',
] as const;

function normalizePath(filePath: string): string {
  return filePath.replace(/^\.\//, '').replace(/^\/+/, '').trim();
}

function hasExt(filePath: string, exts: string[]): boolean {
  const lower = filePath.toLowerCase();
  return exts.some((ext) => lower.endsWith(ext));
}

function isCodeSourceFile(filePath: string): boolean {
  const lower = normalizePath(filePath).toLowerCase();
  if (!lower) return false;
  if (['readme.md', 'run-instructions.md', 'deploy-instructions.md', 'app-manifest.json'].includes(lower)) {
    return false;
  }
  return hasExt(lower, ['.html', '.css', '.js', '.jsx', '.ts', '.tsx', '.json']);
}

function classifyByText(value: string): CodeGenerationMode {
  const normalized = value.toLowerCase();

  if (/\b(game|pong|prototype game|mini game|arcade|platformer)\b/.test(normalized)) {
    return 'small-game-prototype';
  }
  if (/\b(upload|uploader|pdf upload|ingest|processor|processing|convert|converter|pipeline)\b/.test(normalized)) {
    return 'uploader-processor-app';
  }
  if (/\b(crud|internal tool|admin panel|admin app|backoffice|operations tool|workflow tool)\b/.test(normalized)) {
    return 'crud-internal-tool';
  }
  if (/\b(dashboard|analytics|kpi|metrics|reporting)\b/.test(normalized)) {
    return 'dashboard';
  }
  if (/\b(landing page|homepage|hero section|single page)\b/.test(normalized)) {
    return 'landing-page';
  }
  if (/\b(company website|corporate website|business website|agency website|firm website|portfolio website)\b/.test(normalized)) {
    return 'company-website';
  }

  return 'company-website';
}

export function classifyCodeGenerationMode(input: ModeInput): CodeGenerationMode {
  const combined = [input.name, input.description, input.latestRevisionFeedback ?? ''].join(' ').trim();
  const byText = classifyByText(combined);

  if (input.outputType === 'website') {
    if (byText === 'dashboard' || byText === 'crud-internal-tool' || byText === 'uploader-processor-app') {
      return byText;
    }
    return byText === 'company-website' ? 'company-website' : 'landing-page';
  }

  if (input.outputType === 'app') {
    if (byText === 'landing-page' || byText === 'company-website') {
      return 'dashboard';
    }
    return byText;
  }

  return byText;
}

export function getModeLabel(mode: CodeGenerationMode): string {
  const labels: Record<CodeGenerationMode, string> = {
    'landing-page': 'landing page',
    'company-website': 'company website',
    dashboard: 'dashboard',
    'crud-internal-tool': 'CRUD/internal tool',
    'uploader-processor-app': 'uploader/processor app',
    'small-game-prototype': 'small game/prototype',
  };
  return labels[mode];
}

export function detectEntryPoint(files: ExecutionOutputFile[]): string {
  const normalized = files.map((file) => normalizePath(file.path));
  for (const candidate of ENTRY_POINT_PRIORITY) {
    if (normalized.includes(candidate)) return candidate;
  }

  const firstSource = normalized.find((path) => isCodeSourceFile(path));
  return firstSource ?? normalized[0] ?? 'index.html';
}

function buildReadme(params: {
  mode: CodeGenerationMode;
  projectName: string;
  projectDescription: string;
  entryPoint: string;
  files: ExecutionOutputFile[];
  language: AppLanguage;
}): string {
  const title = params.projectName || 'AI Boardroom Generated Project';
  const lines = [
    `# ${title}`,
    '',
    '## Overview',
    params.projectDescription || 'Generated by AI Boardroom code pipeline.',
    '',
    '## Generation Mode',
    getModeLabel(params.mode),
    '',
    '## Entry Point',
    params.entryPoint,
    '',
    '## Files',
    ...params.files.map((file) => `- ${normalizePath(file.path)}`),
    '',
    '## Run',
    'See run-instructions.md',
    '',
    '## Deploy',
    'See deploy-instructions.md',
  ];
  return lines.join('\n');
}

function buildRunInstructions(entryPoint: string): string {
  return [
    '# Run Instructions',
    '',
    '## Local Preview',
    '1. Ensure all generated files are in one folder preserving paths.',
    '2. Start a static server, for example:',
    '```bash',
    'python3 -m http.server 4173',
    '```',
    '3. Open http://localhost:4173 in your browser.',
    '',
    '## Entry Point',
    entryPoint,
  ].join('\n');
}

function buildDeployInstructions(entryPoint: string): string {
  return [
    '# Deploy Instructions',
    '',
    '## Netlify (static deploy)',
    '1. Upload the generated folder as a new site deploy.',
    '2. Ensure the publish directory points to project root.',
    '',
    '## Vercel (static)',
    '1. Import repository/folder containing generated files.',
    '2. Use static framework preset or no-build static deploy.',
    '',
    '## Required Entry Point',
    entryPoint,
  ].join('\n');
}

function buildManifest(params: {
  mode: CodeGenerationMode;
  entryPoint: string;
  files: ExecutionOutputFile[];
  projectName: string;
}): string {
  const payload = {
    schemaVersion: 1,
    type: 'ai-boardroom-code-bundle',
    generationMode: params.mode,
    entryPoint: params.entryPoint,
    projectName: params.projectName || 'Generated Project',
    sourceFiles: params.files.map((file) => normalizePath(file.path)).filter((path) => isCodeSourceFile(path)),
    generatedAt: new Date().toISOString(),
  };
  return JSON.stringify(payload, null, 2);
}

function upsertFile(files: ExecutionOutputFile[], path: string, content: string): ExecutionOutputFile[] {
  const normalizedPath = normalizePath(path);
  const next = [...files];
  const index = next.findIndex((file) => normalizePath(file.path) === normalizedPath);
  if (index >= 0) {
    next[index] = { path: normalizedPath, content: next[index].content || content };
    return next;
  }
  next.push({ path: normalizedPath, content });
  return next;
}

export function stabilizeCodeExecutionBundle(input: StabilizeInput): {
  bundle: ExecutionOutputBundle;
  mode: CodeGenerationMode;
  entryPoint: string;
} {
  const mode = classifyCodeGenerationMode({
    name: input.projectName,
    description: input.projectDescription,
    latestRevisionFeedback: input.latestRevisionFeedback,
    outputType: input.outputType,
  });

  let files = input.bundle.files.map((file) => ({ path: normalizePath(file.path), content: file.content }));
  const entryPoint = detectEntryPoint(files);

  files = upsertFile(
    files,
    'README.md',
    buildReadme({
      mode,
      projectName: input.projectName,
      projectDescription: input.projectDescription,
      entryPoint,
      files,
      language: input.language,
    })
  );
  files = upsertFile(files, 'run-instructions.md', buildRunInstructions(entryPoint));
  files = upsertFile(files, 'deploy-instructions.md', buildDeployInstructions(entryPoint));
  files = upsertFile(
    files,
    'app-manifest.json',
    buildManifest({
      mode,
      entryPoint,
      files,
      projectName: input.projectName,
    })
  );

  const notes = Array.from(
    new Set([
      ...(input.bundle.notes ?? []),
      'Code bundle stabilized with deterministic packaging contract (README/run/deploy/manifest).',
    ])
  );

  const summary = `${input.bundle.summary} [mode=${mode}; entry=${entryPoint}; files=${files.length}]`;

  return {
    bundle: {
      ...input.bundle,
      summary,
      files,
      notes,
    },
    mode,
    entryPoint,
  };
}

export function buildDeterministicCodePackagingNotes(params: {
  bundle: ExecutionOutputBundle;
  mode: CodeGenerationMode;
  entryPoint: string;
}): string {
  const sourceFiles = params.bundle.files
    .map((file) => normalizePath(file.path))
    .filter((path) => isCodeSourceFile(path));

  return [
    '# Bundle Packaging Notes',
    '',
    `- Generation mode: ${getModeLabel(params.mode)}`,
    `- Entry point: ${params.entryPoint}`,
    `- Source file count: ${sourceFiles.length}`,
    `- Total file count: ${params.bundle.files.length}`,
    '',
    '## Contract Files',
    '- README.md',
    '- run-instructions.md',
    '- deploy-instructions.md',
    '- app-manifest.json',
    '',
    '## Source Set',
    ...sourceFiles.map((path) => `- ${path}`),
  ].join('\n');
}

export function buildDeterministicCodeFinalSummary(params: {
  bundle: ExecutionOutputBundle;
  mode: CodeGenerationMode;
  entryPoint: string;
  reviewNotes?: string | null;
  packagingNotes?: string | null;
}): string {
  const lines = [
    '# Final Summary',
    '',
    `Generation mode: ${getModeLabel(params.mode)}`,
    `Entry point: ${params.entryPoint}`,
    `Generated files: ${params.bundle.files.length}`,
    '',
    'The preview and exported bundle use the same generated source set from generated-files.json.',
  ];

  if (params.reviewNotes?.trim()) {
    lines.push('', '## Reviewer Notes', params.reviewNotes.trim());
  }

  if (params.packagingNotes?.trim()) {
    lines.push('', '## Packaging Notes', params.packagingNotes.trim());
  }

  return lines.join('\n');
}
